services:
    qa_lander1:
        build:
            context: ./partner/lander1
            dockerfile: docker/Dockerfile
        restart: always
        volumes:
            - ./partner/lander1/docker/log:/var/log/nginx
            - ./partner/lander1/docker/conf.d:/etc/nginx/conf.d
            - ./partner/lander1/src:/var/www/html
        environment:
            NGINX_ENTRYPOINT_QUIET_LOGS: 1
        networks:
            permate_network:
                aliases:
                    - qa_lander1

    qa_lander2:
        build:
            context: ./partner/lander2
            dockerfile: docker/Dockerfile
        restart: always
        volumes:
            - ./partner/lander2/docker/log:/var/log/nginx
            - ./partner/lander2/docker/conf.d:/etc/nginx/conf.d
            - ./partner/lander2/src:/var/www/html
        environment:
            NGINX_ENTRYPOINT_QUIET_LOGS: 1
        networks:
            permate_network:
                aliases:
                    - qa_lander2

    qa_lander3:
        build:
            context: ./partner/lander3
            dockerfile: docker/Dockerfile
        restart: always
        volumes:
            - ./partner/lander3/docker/log:/var/log/nginx
            - ./partner/lander3/docker/conf.d:/etc/nginx/conf.d
            - ./partner/lander3/src:/var/www/html
        environment:
            NGINX_ENTRYPOINT_QUIET_LOGS: 1
        networks:
            permate_network:
                aliases:
                    - qa_lander3

    qa_lander4:
        build:
            context: ./partner/lander4
            dockerfile: docker/Dockerfile
        restart: always
        volumes:
            - ./partner/lander4/docker/log:/var/log/nginx
            - ./partner/lander4/docker/conf.d:/etc/nginx/conf.d
            - ./partner/lander4/src:/var/www/html
        environment:
            NGINX_ENTRYPOINT_QUIET_LOGS: 1
        networks:
            permate_network:
                aliases:
                    - qa_lander4

    qa_lander5:
        build:
            context: ./partner/lander5
            dockerfile: docker/Dockerfile
        restart: always
        volumes:
            - ./partner/lander5/docker/log:/var/log/nginx
            - ./partner/lander5/docker/conf.d:/etc/nginx/conf.d
            - ./partner/lander5/src:/var/www/html
        environment:
            NGINX_ENTRYPOINT_QUIET_LOGS: 1
        networks:
            permate_network:
                aliases:
                    - qa_lander5

    qa_lander6:
        build:
            context: ./partner/lander6
            dockerfile: docker/Dockerfile
        restart: always
        volumes:
            - ./partner/lander6/docker/log:/var/log/nginx
            - ./partner/lander6/docker/conf.d:/etc/nginx/conf.d
            - ./partner/lander6/src:/var/www/html
        environment:
            NGINX_ENTRYPOINT_QUIET_LOGS: 1
        networks:
            permate_network:
                aliases:
                    - qa_lander6

    qa_lander7:
        build:
            context: ./partner/lander7
            dockerfile: docker/Dockerfile
        restart: always
        volumes:
            - ./partner/lander7/docker/log:/var/log/nginx
            - ./partner/lander7/docker/conf.d:/etc/nginx/conf.d
            - ./partner/lander7/src:/var/www/html
        environment:
            NGINX_ENTRYPOINT_QUIET_LOGS: 1
        networks:
            permate_network:
                aliases:
                    - qa_lander7

    qa_lander8:
        build:
            context: ./partner/lander8
            dockerfile: docker/Dockerfile
        restart: always
        volumes:
            - ./partner/lander8/docker/log:/var/log/nginx
            - ./partner/lander8/docker/conf.d:/etc/nginx/conf.d
            - ./partner/lander8/src:/var/www/html
        environment:
            NGINX_ENTRYPOINT_QUIET_LOGS: 1
        networks:
            permate_network:
                aliases:
                    - qa_lander8

    qa_lander9:
        build:
            context: ./partner/lander9
            dockerfile: docker/Dockerfile
        restart: always
        volumes:
            - ./partner/lander9/docker/log:/var/log/nginx
            - ./partner/lander9/docker/conf.d:/etc/nginx/conf.d
            - ./partner/lander9/src:/var/www/html
        environment:
            NGINX_ENTRYPOINT_QUIET_LOGS: 1
        networks:
            permate_network:
                aliases:
                    - qa_lander9

    qa_offer1:
        build:
            context: ./offer/offer1
            dockerfile: docker/Dockerfile
        restart: always
        volumes:
            - ./offer/offer1/docker/log:/var/log/nginx
            - ./offer/offer1/docker/conf.d:/etc/nginx/conf.d
            - ./offer/offer1/src:/var/www/html
        environment:
            NGINX_ENTRYPOINT_QUIET_LOGS: 1
        networks:
            permate_network:
                aliases:
                    - qa_offer1

    qa_offer2:
        build:
            context: ./offer/offer2
            dockerfile: docker/Dockerfile
        restart: always
        volumes:
            - ./offer/offer2/docker/log:/var/log/nginx
            - ./offer/offer2/docker/conf.d:/etc/nginx/conf.d
            - ./offer/offer2/src:/var/www/html
        environment:
            NGINX_ENTRYPOINT_QUIET_LOGS: 1
        networks:
            permate_network:
                aliases:
                    - qa_offer2

    qa_offer3:
        build:
            context: ./offer/offer3
            dockerfile: docker/Dockerfile
        restart: always
        volumes:
            - ./offer/offer3/docker/log:/var/log/nginx
            - ./offer/offer3/docker/conf.d:/etc/nginx/conf.d
            - ./offer/offer3/src:/var/www/html
        environment:
            NGINX_ENTRYPOINT_QUIET_LOGS: 1
        networks:
            permate_network:
                aliases:
                    - qa_offer3

    qa_offer4:
        build:
            context: ./offer/offer4
            dockerfile: docker/Dockerfile
        restart: always
        volumes:
            - ./offer/offer4/docker/log:/var/log/nginx
            - ./offer/offer4/docker/conf.d:/etc/nginx/conf.d
            - ./offer/offer4/src:/var/www/html
        environment:
            NGINX_ENTRYPOINT_QUIET_LOGS: 1
        networks:
            permate_network:
                aliases:
                    - qa_offer4

    qa_offer5:
        build:
            context: ./offer/offer5
            dockerfile: docker/Dockerfile
        restart: always
        volumes:
            - ./offer/offer5/docker/log:/var/log/nginx
            - ./offer/offer5/docker/conf.d:/etc/nginx/conf.d
            - ./offer/offer5/src:/var/www/html
        environment:
            NGINX_ENTRYPOINT_QUIET_LOGS: 1
        networks:
            permate_network:
                aliases:
                    - qa_offer5

    qa_offer6:
        build:
            context: ./offer/offer6
            dockerfile: docker/Dockerfile
        restart: always
        volumes:
            - ./offer/offer6/docker/log:/var/log/nginx
            - ./offer/offer6/docker/conf.d:/etc/nginx/conf.d
            - ./offer/offer6/src:/var/www/html
        environment:
            NGINX_ENTRYPOINT_QUIET_LOGS: 1
        networks:
            permate_network:
                aliases:
                    - qa_offer6

    qa_impression:
        build:
            context: ./impression
            dockerfile: docker/Dockerfile
        restart: always
        volumes:
            - ./impression/docker/log:/var/log/nginx
            - ./impression/docker/conf.d:/etc/nginx/conf.d
            - ./impression/src:/var/www/html
        environment:
            NGINX_ENTRYPOINT_QUIET_LOGS: 1
        networks:
            permate_network:
                aliases:
                    - qa_impression
networks:
    permate_network:
        external: true
        name: permate_network