services:
    lander1:
        build:
            context: .
            dockerfile: docker/lander1.Dockerfile
        restart: always
        volumes:
            - ./docker/log:/var/log/nginx
            - ./docker/conf.d:/etc/nginx/conf.d
        environment:
            NGINX_ENTRYPOINT_QUIET_LOGS: 1
        ports:
            - 1001:80
        networks:
            permate_network:
                aliases:
                    - lander1
    lander2:
        build:
            context: .
            dockerfile: docker/lander2.Dockerfile
        restart: always
        volumes:
            - ./docker/log:/var/log/nginx
            - ./docker/conf.d:/etc/nginx/conf.d
        environment:
            NGINX_ENTRYPOINT_QUIET_LOGS: 1
        ports:
            - 1002:80
        networks:
            permate_network:
                aliases:
                    - lander2
    lander3:
        build:
            context: .
            dockerfile: docker/lander3.Dockerfile
        restart: always
        volumes:
            - ./docker/log:/var/log/nginx
            - ./docker/conf.d:/etc/nginx/conf.d
        environment:
            NGINX_ENTRYPOINT_QUIET_LOGS: 1
        ports:
            - 1003:80
        networks:
            permate_network:
                aliases:
                    - lander3
    lander4:
        build:
            context: .
            dockerfile: docker/lander4.Dockerfile
        restart: always
        volumes:
            - ./docker/log:/var/log/nginx
            - ./docker/conf.d:/etc/nginx/conf.d
        environment:
            NGINX_ENTRYPOINT_QUIET_LOGS: 1
        ports:
            - 1004:80
        networks:
            permate_network:
                aliases:
                    - lander4
    lander5:
        build:
            context: .
            dockerfile: docker/lander5.Dockerfile
        restart: always
        volumes:
            - ./docker/log:/var/log/nginx
            - ./docker/conf.d:/etc/nginx/conf.d
        environment:
            NGINX_ENTRYPOINT_QUIET_LOGS: 1
        ports:
            - 1005:80
        networks:
            permate_network:
                aliases:
                    - lander5
    lander6:
        build:
            context: .
            dockerfile: docker/lander6.Dockerfile
        restart: always
        volumes:
            - ./docker/log:/var/log/nginx
            - ./docker/conf.d:/etc/nginx/conf.d
        environment:
            NGINX_ENTRYPOINT_QUIET_LOGS: 1
        ports:
            - 1006:80
        networks:
            permate_network:
                aliases:
                    - lander6
networks:
    permate_network:
        external: true
        name: permate_network