-   hosts: all
    name: Deploy applications on Docker compose
    remote_user: ubuntu
    become: yes
    tasks:
      - name: Run git fetch
        command: git fetch -a
        args:
          chdir: /home/ubuntu/landing

      - name: Run git pull
        command: git pull
        args:
          chdir: /home/ubuntu/landing
