services:
    haproxy:
        image: haproxy:2.8-alpine
        restart: unless-stopped
        ports:
            - "80:80"
        volumes:
            - ./config/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
        healthcheck:
            test: [ "CMD-SHELL", "echo 'show info' | nc -U /run/haproxy/admin.sock | grep -q 'Process_id'" ]
            interval: 2s
            timeout: 5s
            retries: 2
        networks:
            permate_network:
                aliases:
                    - haproxy
networks:
    permate_network:
        external: true
        driver: bridge
        name: permate_network
