services:
    haproxy:
        image: haproxy:latest
        restart: unless-stopped
        ports:
            - "80:80"
        volumes:
            - ./config/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
        networks:
            permate_network:
        healthcheck:
            test: [ "CMD-SHELL", "echo 'show info' | nc -U /run/haproxy/admin.sock | grep -q 'Process_id'" ]
            interval: 2s
            timeout: 5s
            retries: 2

networks:
    permate_network:
        external: true
        driver: bridge
